[project]
name = "Loreal-Shades-Clustering"
version = "0.1.0"
description = "Ce projet a été réalisé dans un cadre académique en collaboration avec L’Oréal, qui en a proposé le sujet et accompagné son développement. Il porte sur la problématique du shades clustering, c’est-à-dire la classification et l’organisation de nuances de teintes afin d’améliorer leur représentation et leur cohérence dans des applications industrielles. Le travail a été mené sous le double encadrement des équipes de L’Oréal, apportant une expertise métier, et des tuteurs académiques de Télécom Paris, garantissant la rigueur scientifique et méthodologique du projet. Cette collaboration a permis d’aborder le sujet selon une approche à la fois professionnelle, technique et pédagogique."
authors = [
    {name = "Mohamed Khalil OUNIS",email = "khalilounis10@gmail.com"},
    {name = "Oussama BELHAJ RHOUMA",email = "oussama10rhouma@gmail.com"},
    {name = "Lina RHIATI HAZIME",email = "lina.rhiati2@gmail.com"},
    {name = "Reda ELWARADI",email = "you@example.com"},
    {name = "Kamal BELMAJDOUB",email = "you@example.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
